import json


'''
   Note: I added to the below three additional parts of speech:
      1. reflexive verb (125 entries)
      2. transitive or reflexive verb (one entry)
      3. intransitive or reflexive verb (three entries)

'''
pos_dict = {"(m.)": "masculine noun",
"(adj.)": "adjective",
"(n.)": "neuter noun",
"(f.)": "feminine noun",
"(v.)": "verb",
"(v. intrans.)": "intransitive verb",
"(conj.)": "conjuntion",
"(adv.)": "adverb",
"(prep.)": "preposition",
"(f./n/)": "feminine or neuter noun",
"(interj.)": "interjection",
"(place)": "noun (place)",
"(f./n.)": "feminine or neuter noun",
"(m./n.)": "masculine or neuter noun",
"(prep. phr.)": "prepositional phrase",
"(phrase)": "phrase",
"(pl.)": "plural noun",
"(adv. phrase)": "adverbial phrase",
"(name)": "noun (name)",
"(m./f.)": "masculine or feminine noun",
"(number)": "number",
"(m`.)": "masculine noun",
"(pron. 3rd pers. accus.)": "pronoun",
"(n./m.)": "neuter or masculine noun",
"(particle)": "particle",
"(contr.)": "contraction (preposition + article)",
"(pron., the same form in all cases)": "pronoun",
"(indef. article)": "indefinite article",
"(def. article)": "definite article",
"(adj. possesive)": "possessive pronoun",
"(plae)": "place",
"(expression)": "expression",
"(f./m.)": "feminine or masculine noun",
"(pron. 2nd pers. sing. nom. informal)": "pronoun",
"(prep. contraction of iber and dem)": "contraction (preposition + article)",
"(pron.)": "pronoun",
"(m./interj.)": "interjection or masculine noun phrase",
"(adj. predicate)": "predicative adjective",
"(num.)": "number",
"(interj., imperative 2nd person plural or 1st person formal)": "interjection",
"(prefix)": "prefix",
"(adj. /prep. phrase)": "prepositional or adjectival phrase",
"(phrase.)": "phrase",
"(pron. demonstrative)": "demonstrative determiner or pronoun",
"(b.)": "verb",
"(n./f.)": "neuter or feminine noun",
"(v. periphrastic)": "periphrastic verb",
"(vt./vi.)": "transitive or intransitive verb",
"(prep. phrase)": "prepositional phrase",
"(n. pl.)": "plural noun",
"(pers. pronoun 1st person plural)": "possessive pronoun",
"(v. auxiliary)": "verb",
"(pron. 1st pers. sing. dative)": "pronoun",
"(expression; interj.)": "expression or interjection",
"(title)": "title",
"(adv. compl.)": "adverb",
"(f.) (name)": "place",
"f.": "feminine noun",
"(adv./interj.)": "interjection",
"(m. (grammar))": "masculine noun",
"(adverbial complement)": "preposition",
"m.": "masculine noun",
"(prep. compound) combination of durkh and dem": "contraction (preposition + article)",
"(v. phrase)": "verb phrase",
"(pers. pronoun 2nd pers. plural /2nd pers. sing., formal)": "possessive pronoun",
"(interj./adv.)": "interjection",
"(m./n/)": "masculine or neuter noun",
"(suffix)": "suffix",
"(expression/idiom)": "idiom",
"(interj., imperative 1st person familiar)": "interjection",
"(adj. /pron./adv.)": "adverb or pronoun",
"(m./f.  (grammar))": "masculine or feminine noun",
"(pers. pronoun, 2nd person singular possesive)": "possessive pronoun",
"(pred. adj.)": "adjective",
"(phrase/interj.)": "interjection",
"(abbrev.)": "abbreviation",
"n.": "neuter noun",
"(f. (grammar))": "feminine noun",
"adj.": "adjective",
"(pers. pronoun 2nd pers. sing.)": "possessive pronoun",
"(m. inflected)": "masculine noun",
"(title abbrev.)": "title",
"(rel. pron.)": "relative pronoun",
"(name.)": "name",
"(pl. dimin.)": "plural diminutive noun",
"(adj uninflected.)": "adjective",
"(aux. v.)": "verb",
"(M.)": "masculine noun",
"(prep.) (comb. of 'in' and 'dem')": "contraction (preposition + article)",
"(v. sing. past part.)": "verb (past participle/present perfect)",
"(pron., 1st person plural, dative and accusative)": "pronoun",
"(adv.phrase)": "adverbial phrase",
"(interj., expression)": "phrase",
"(int.)": "interjection",
"(prep. phrase)(contraction of mit and dem)": "contraction (preposition + article)",
"v.)": "verb",
"(prep. contraction)": "contraction (preposition + article)",
"(imp. v.)": "imperative verb phrase",
"(v intrans.)": "verb",
"(pron. first person masculine)": "pronoun",
"(phrase/curse)": "phrase (curse)",
"(prep. contraction of in and em)": "contraction (preposition + article)",
"(pron. 1st pers. sing. accusative)": "pronoun",
"(adv. pharase)": "adverbial phrase",
"(pers. pron, 2nd person singular)": "possessive pronoun",
"(interjection)": "interjection",
"(prep./conj.)": "preposition or conjunction",
"(adj. /interj.)": "adjective or interjection",
"v.": "verb",
"(v. )": "verb",
"(curse)": "phrase (curse)",
"(adj. /adv.)": "adjective or adverb",
"(pron., 1st person singular)": "pronoun",
"(adv. contraction)": "contraction (adverb + article)",
"(pron. 2nd pers. pl. dat. and acc. / formal)": "pronoun",
"(pers. pronoun, 1st person singular)": "possessive pronoun",
"(epithet)": "epithet",
"(f./pl.)": "feminine or plural noun",
"(interrogative determiner)": "interrogative determiner",
"(distributive determiner or pronoun)": "distributive determiner or pronoun",
"(demonstrative determiner or pronoun)": "demonstrative determiner or pronoun",
"(interrogative determiner or pronoun)": "interrogative determiner or pronoun",
"(adj. phrase)": "adjectival phrase",
"(n. phrase)": "noun phrase"}

f = open('./words.json', 'r+', encoding='UTF8')
words = json.load(f)

result = ['[\n']

for i in range(len(words) -1):
   words[i][3] = pos_dict[words[i][3]]
   result.append('\t' + str(json.dumps(words[i], ensure_ascii=False).encode('utf8').decode()) + ',\n')

words[len(words) -1][3] = pos_dict[words[len(words) -1][3]]
result.append('\t' + str(json.dumps(words[len(words) -1], ensure_ascii=False).encode('utf8').decode()))
result.append('\n]')

f.seek(0)
f.truncate()
f.writelines(result)
f.close()
